from sikuli import *
import logging
import myTools

#---------------------------------------------------#
def Create_Task():
#---------------------------------------------------#

    myTools.sectionStartTimeStamp("create task")

    logging.debug('Create_Task')

    logging.debug('- open task list')
    type("n",KeyModifier.ALT)
    type("f")
    time.sleep(1)

    logging.debug('- create new task')
    type("n",KeyModifier.CTRL)

    logging.debug('  - names')
    type("Skipping")
    type(Key.TAB)
    type("1234")
    type(Key.ENTER)
    type("Skipping Around in Circles")

    type(Key.TAB)
    type("o")
    type(Key.TAB)

    time.sleep(1)
    logging.debug('  - rates')
    type(Key.TAB)    
    type("1")
    type(Key.TAB)    
    type("2")    
    type(Key.TAB)    
    type("3")
    type(Key.TAB)    
    type("4")    
    type(Key.TAB)    
    type("5")
    type(Key.TAB)    
    type("6")    
    type(Key.TAB)    
    type("7")
    type(Key.TAB)    
    type("8")    
    type(Key.TAB)    
    type("9")
    type(Key.TAB)    
    type("10")    
    type(Key.TAB)    
    type("11")
    type(Key.TAB)    
    type("12")    
    type(Key.TAB)    
    type("13")
    type(Key.TAB)    
    type("14")    
    type(Key.TAB)    
    type("15")
    type(Key.TAB)    
    type("16")    
    type(Key.TAB)    
    type("17")
    type(Key.TAB)    
    type("18")    
    type(Key.TAB)    
    type("19")
    type(Key.TAB)    
    type("20")    

    logging.debug('  - defaults')
    time.sleep(1)
    myTools.pressTAB(2)
    type("11.2")    
    type(Key.TAB)
    type("11.1")    
    type(Key.TAB)
    type("b")
    type(Key.TAB)
    type("o")
    type(Key.TAB)
    type("Frolicking and Playing")

    logging.debug('- save and close task list')
    type("s",KeyModifier.CTRL)
    
    type(Key.F4,KeyModifier.CTRL)
    time.sleep(1)    
    type(Key.F4,KeyModifier.CTRL)

    myTools.sectionEndTimeStamp()